# Generated by Django 5.0.1 on 2024-01-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='negative_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publication',
            name='positive_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publication',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
