# Generated by Django 5.0.1 on 2024-01-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_negative_votes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='negative_votes',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='positive_votes',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='rating',
        ),
        migrations.AlterField(
            model_name='publication',
            name='article',
            field=models.CharField(),
        ),
    ]
