# Generated by Django 5.0.1 on 2024-01-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_remove_publication_negative_votes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
